# cmake -DOUT=physics_hash.hpp -DFILES="a;b;c" -P physics_hash.cmake
# One hash over the physics source (solver, voxeliser, their shaders): part
# of every flow-cache key, so any edit to them invalidates every cached flow
# -- a stale cache silently showing old physics is worse than none.
set(all "")
foreach(f IN LISTS FILES)
    file(SHA256 "${f}" h)
    string(APPEND all "${h}")
endforeach()
string(SHA256 digest "${all}")
string(SUBSTRING "${digest}" 0 16 short)
set(text "// Generated by cmake/physics_hash.cmake -- do not edit.
#pragma once
namespace windoa { inline constexpr const char* kPhysicsHash = \"${short}\"; }
")
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
    if(old STREQUAL text)
        return()
    endif()
endif()
file(WRITE "${OUT}" "${text}")
